export const T = {
  green50: "#E8F5EE", green100: "#C3E6D0", green200: "#8FCBAA",
  green400: "#3DA068", green600: "#1E7847", green800: "#0D4E2C", green900: "#062E19",
  stone50: "#F7F5F0", stone100: "#EAE7DE", stone200: "#D4CFBF",
  stone400: "#9E9882", stone600: "#6B6554", stone800: "#3D3A30", stone900: "#1E1C16",
  amber50: "#FDF4E3", amber200: "#F5CC7F", amber600: "#C47F0A",
  red50: "#FDF0F0", red200: "#F5A8A8", red600: "#C43333",
  white: "#FDFCF9",
};

export const S = {
  screen: { minHeight: "100vh", background: T.stone50, fontFamily: "'DM Sans', sans-serif" },
  main: { maxWidth: 700, margin: "0 auto", padding: "16px 12px 100px" },
  header: { background: T.green800, padding: "16px 16px 0", position: "sticky", top: 0, zIndex: 200 },
  headerTop: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 14 },
  logo: { display: "flex", alignItems: "center", gap: 8, fontSize: 22, fontFamily: "'DM Serif Display', serif", color: T.green50, fontWeight: 400 },
  headerBtn: { background: "rgba(255,255,255,.12)", color: T.green100, border: "none", borderRadius: 8, padding: "6px 12px", fontSize: 12, fontFamily: "'DM Sans', sans-serif", fontWeight: 500, cursor: "pointer" },
  tabsWrap: { display: "flex", overflowX: "auto" },
  tab: { flexShrink: 0, padding: "10px 16px", fontSize: 13, fontWeight: 500, color: "rgba(255,255,255,.55)", cursor: "pointer", borderBottom: "2.5px solid transparent", whiteSpace: "nowrap", transition: "all .15s" },
  tabActive: { color: "#fff", borderBottomColor: T.green200 },
  card: { background: T.white, borderRadius: 16, border: `1px solid ${T.stone100}`, padding: 16, marginBottom: 10, boxShadow: "0 1px 2px rgba(30,24,10,.06)" },
  cardTitle: { fontSize: 15, fontWeight: 600, marginBottom: 12, color: T.stone800 },
  formLabel: { display: "block", fontSize: 11, fontWeight: 600, letterSpacing: ".05em", textTransform: "uppercase", color: T.stone600, marginBottom: 4 },
  formGroup: { marginBottom: 12 },
  input: { width: "100%", padding: "10px 12px", border: `1.5px solid ${T.stone200}`, borderRadius: 10, fontSize: 14, fontFamily: "'DM Sans', sans-serif", color: T.stone900, background: T.white, outline: "none", boxSizing: "border-box" },
  textarea: { width: "100%", padding: "10px 12px", border: `1.5px solid ${T.stone200}`, borderRadius: 10, fontSize: 14, fontFamily: "'DM Sans', sans-serif", color: T.stone900, background: T.white, outline: "none", height: 72, resize: "vertical", lineHeight: 1.5, boxSizing: "border-box" },
  select: { width: "100%", padding: "10px 12px", border: `1.5px solid ${T.stone200}`, borderRadius: 10, fontSize: 14, fontFamily: "'DM Sans', sans-serif", color: T.stone900, background: T.white, outline: "none", appearance: "none", WebkitAppearance: "none", boxSizing: "border-box" },
  btn: { display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 6, padding: "10px 18px", borderRadius: 10, fontSize: 14, fontWeight: 600, fontFamily: "'DM Sans', sans-serif", cursor: "pointer", border: `1.5px solid ${T.stone200}`, background: T.white, color: T.stone800 },
  btnPrimary: { background: T.green600, color: "#fff", borderColor: T.green600 },
  btnDanger: { background: T.red50, color: T.red600, borderColor: T.red200 },
  btnAmber: { background: T.amber50, color: T.amber600, borderColor: T.amber200 },
  btnSm: { padding: "6px 10px", fontSize: 12 },
  btnFull: { width: "100%" },
  badge: { display: "inline-block", fontSize: 11, fontWeight: 600, padding: "3px 9px", borderRadius: 20 },
  chip: { display: "inline-block", fontSize: 11, fontWeight: 500, padding: "2px 8px", borderRadius: 20, background: T.green50, color: T.green800 },
  chips: { display: "flex", flexWrap: "wrap", gap: 4, marginTop: 6 },
  sectionLabel: { fontSize: 11, fontWeight: 600, letterSpacing: ".06em", textTransform: "uppercase", color: T.stone400, marginBottom: 8 },
  emptyState: { textAlign: "center", color: T.stone400, fontSize: 14, padding: "40px 20px" },
  emptyIcon: { fontSize: 36, marginBottom: 8 },
  flexBetween: { display: "flex", alignItems: "center", justifyContent: "space-between" },
  pedidoCard: { background: T.white, borderRadius: 16, border: `1px solid ${T.stone100}`, marginBottom: 10, boxShadow: "0 1px 2px rgba(30,24,10,.06)", overflow: "hidden" },
  pedidoHeader: { padding: "14px 16px 10px", display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 8, borderBottom: `1px solid ${T.stone100}` },
  pedidoCliente: { fontSize: 16, fontWeight: 600, fontFamily: "'DM Serif Display', serif" },
  pedidoMeta: { fontSize: 12, color: T.stone400, marginTop: 2 },
  pedidoBody: { padding: "10px 16px" },
  pedidoItem: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "5px 0", borderBottom: `1px dashed ${T.stone100}`, fontSize: 13 },
  pedidoItemNome: { color: T.stone800, fontWeight: 500 },
  pedidoItemForn: { color: T.stone400, fontSize: 11 },
  pedidoItemQtd: { fontWeight: 600, color: T.green600, fontSize: 14, whiteSpace: "nowrap" },
  pedidoObs: { fontSize: 12, color: T.stone600, background: T.stone50, borderRadius: 8, padding: "8px 10px", marginTop: 8 },
  pedidoFooter: { padding: "10px 16px", background: T.stone50, display: "flex", gap: 6, alignItems: "center", flexWrap: "wrap", borderTop: `1px solid ${T.stone100}` },
  filtrosBar: { display: "flex", gap: 6, marginBottom: 12, overflowX: "auto", paddingBottom: 4 },
  filtroChip: { flexShrink: 0, padding: "5px 12px", borderRadius: 20, fontSize: 12, fontWeight: 500, background: T.white, border: `1.5px solid ${T.stone200}`, color: T.stone600, cursor: "pointer", whiteSpace: "nowrap" },
  filtroChipActive: { background: T.green600, color: "#fff", borderColor: T.green600 },
  resumoGroup: { background: T.white, borderRadius: 16, border: `1px solid ${T.stone100}`, marginBottom: 12, overflow: "hidden" },
  resumoHeader: { padding: "12px 16px", background: T.green800, display: "flex", alignItems: "center", justifyContent: "space-between" },
  resumoHeaderNome: { fontSize: 14, fontWeight: 600, color: T.green50, fontFamily: "'DM Serif Display', serif" },
  histGrupo: { marginBottom: 20 },
  histAvatar: { width: 38, height: 38, borderRadius: "50%", background: T.green600, color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14, fontWeight: 700, fontFamily: "'DM Serif Display', serif", flexShrink: 0 },
  histClienteHeader: { display: "flex", alignItems: "center", gap: 10, marginBottom: 8 },
  histPedido: { background: T.white, border: `1px solid ${T.stone100}`, borderRadius: 10, padding: "10px 14px", marginBottom: 6, marginLeft: 48 },
  fornItem: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "10px 0", borderBottom: `1px solid ${T.stone100}` },
  fornName: { fontSize: 14, fontWeight: 600 },
  fornMeta: { fontSize: 12, color: T.stone400, marginTop: 2 },
  overlay: { position: "fixed", inset: 0, background: "rgba(30,24,10,.45)", zIndex: 500, display: "flex", alignItems: "flex-end", justifyContent: "center" },
  modal: { background: T.white, borderRadius: "16px 16px 0 0", padding: "20px 16px 32px", width: "100%", maxWidth: 700, maxHeight: "92vh", overflowY: "auto" },
  modalTitle: { fontFamily: "'DM Serif Display', serif", fontSize: 22, marginBottom: 16, color: T.green800 },
  modalClose: { float: "right", background: T.stone100, border: "none", borderRadius: "50%", width: 32, height: 32, fontSize: 18, cursor: "pointer", color: T.stone600, display: "flex", alignItems: "center", justifyContent: "center", marginLeft: 8 },
  acWrap: { position: "relative" },
  acList: { position: "absolute", top: "calc(100% + 2px)", left: 0, right: 0, background: T.white, border: `1.5px solid ${T.green400}`, borderRadius: 10, zIndex: 300, maxHeight: 160, overflowY: "auto", boxShadow: "0 4px 16px rgba(30,24,10,.1)" },
  acItem: { padding: "8px 12px", fontSize: 13, cursor: "pointer" },
  prodTable: { width: "100%", borderCollapse: "collapse", fontSize: 13, background: T.white },
  prodTableTh: { textAlign: "left", padding: "10px 12px", fontSize: 11, letterSpacing: ".06em", textTransform: "uppercase", color: T.stone600, background: T.stone50, borderBottom: `1px solid ${T.stone100}` },
  prodTableTd: { padding: "10px 12px", borderBottom: `1px solid ${T.stone100}`, verticalAlign: "top" },
};
